-- 화장품 --
CREATE SEQUENCE CSMT_SEQ MAXVALUE 999999;

CREATE TABLE COSMETICS  (
    COSNUM NUMBER(6) CONSTRAINT CSMT_PK PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL, 
    PRICE NUMBER(8) NOT NULL,
    COMPANY VARCHAR2(50) NOT NULL,
    VOLUME NUMBER(5) NOT NULL
);


-- 위험 성분 --
CREATE SEQUENCE HRMFLINGRD_SEQ MAXVALUE 999999;

CREATE TABLE HARMFULINGRD(
    ingrdNum NUMBER(6),
    ingrdName VARCHAR2(50),
    sideEffect VARCHAR2(100),
    CONSTRAINT PK_INGRDNUM PRIMARY KEY(ingrdNUM)
);


-- 위험 화장품 --
CREATE SEQUENCE HRMFLCOS_SEQ MAXVALUE 999999;

CREATE TABLE HARMFULCOS  (
    NUM NUMBER(6) CONSTRAINT HFC_PK PRIMARY KEY,
    COSNUM NUMBER(6) NOT NULL ,
    INGRDNUM NUMBER(6) NOT NULL
);
ALTER TABLE HARMFULCOS ADD CONSTRAINT FK_HARMFULCOS_COSNUM FOREIGN KEY(COSNUM) REFERENCES COSMETICS(COSNUM);
ALTER TABLE HARMFULCOS ADD CONSTRAINT FK_HARMFULCOS_INGRDNUM FOREIGN KEY(INGRDNUM) REFERENCES HARMFULINGRD(INGRDNUM);


-- 회원 --
CREATE TABLE MEMBER(
    id VARCHAR2(50),
    name VARCHAR2(50),
    passwd VARCHAR2(50),
    age NUMBER(4),
	skinType VARCHAR2(50),
    CONSTRAINT PK_MEMBER_ID PRIMARY KEY(id)
);


-- 로그 --
CREATE SEQUENCE LOG_SEQ MAXVALUE 99999999;

CREATE TABLE LOG(
    loginNum NUMBER(8),
    loginDate DATE,
    logoutDate DATE,
    memberId VARCHAR2(50),
    CONSTRAINT LOG_pk PRIMARY KEY(loginNum),
    FOREIGN KEY (memberId) REFERENCES MEMBER(id)
);


-- 게시글(리뷰) --
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999;

CREATE TABLE board(
    boardNum NUMBER(6),
    boardTitle VARCHAR2(50) NOT NULL,
    boardContent VARCHAR2(2000) NOT NULL,
    writeTime DATE NOT NULL,
    starRating NUMBER(1) NOT NULL,
    memberId VARCHAR2(50),
    COSNUM NUMBER(8),
    constraint PK_BOARD_BOARDNUM PRIMARY KEY(boardNum),
    constraint FK_BOARD_MEMBERID FOREIGN KEY(memberId) REFERENCES member(ID),
    constraint FK_BOARD_COSNUM FOREIGN KEY(COSNUM) REFERENCES cosmetics(COSNUM)
);


-- 댓글 --
CREATE SEQUENCE CMNT_SEQ MAXVALUE 9999999999;

CREATE TABLE CMNT(
    num NUMBER(10),
    content VARCHAR2(2000) NOT NULL,
    CommentTime DATE NOT NULL,
    memberId VARCHAR2(50),
    boardNum NUMBER(10), 
    constraint PK_COMMENT_NUM PRIMARY KEY(num),
    constraint FK_COMMENT_MEMBERID FOREIGN KEY(memberId) REFERENCES member(ID),
    constraint FK_COMMENT_BOARDNUM FOREIGN KEY(boardNum) REFERENCES board(boardNum)
);